### ISSUE TITLE
Please testing

### ISSUE THREAD

**Issue by KarenKiK** [KarenKiK/Ulmart#1]
#1 @coursar 
Добрый день. Так и не смог добавить в контроллер и в html файл, кнопки удалить и редактировать.
Точнее сами кнопки то добавить не проблема, но привязать к ним действия так и не получилось.

Все остальное вроде работает, поиск, добавление разных обьектов и детали по ним.

**Comment by KarenKiK** [comment]
Удалить в сервисе прописал, пока что так и не понял как "РЕДАКТИРОВАТЬ", помогите пожалуйста.

**Comment by coursar** [comment]
На каждый тип продукта вы делаете либо:
1. Отдельные страницы редактирования/добавления
2. Либо одну страницу, но в странице через th-if разруливаете то, какие поля показывать
